### ISSUE TITLE
`templates` options not honoured?

### ISSUE THREAD

**Issue by netsgnut** [skratchdot/react-bootstrap-multiselect#12]
[`get-options.js`](https://github.com/skratchdot/react-bootstrap-multiselect/blob/master/lib/get-options.js) seems to be a whitelist for the `react-bootstrap-multiselect` to know which properties to pass to the underlying `bootstrap-multiselect` library. However it does not have a `templates` on list, which means the templates cannot be [customized](https://github.com/davidstutz/bootstrap-multiselect/blob/v0.9.13/dist/js/bootstrap-multiselect.js#L335).

I have tried to add "templates" manually to the aforementioned file and it works. Maybe we should update the gulp script for that? Thanks.

**Comment by skratchdot** [comment]
@netsgnut - thanks for the suggestion! I made this change and published a new version.

**Comment by netsgnut** [comment]
Awesome! Thanks :+1:
