### ISSUE TITLE
React >0.14.0 Warnings: .getDOMNode()

### ISSUE THREAD

**Issue by mgruschetzki** [skratchdot/react-bootstrap-multiselect#21]
Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by MultiSelect.

The problem is on line 46 of index.js:
`$this.$multiselect = $($this.refs.multiselect.getDOMNode()); `
In React >0.14.0 the dom node is direct in ref, so below should be fixed:
`$this.$multiselect = $($this.refs.multiselect); `

**Comment by skratchdot** [comment]
This should be fixed in 6bd385ee42144d89973123bbf0414377d30762af (published to npm as v1.0.0)
