### ISSUE TITLE
enableFiltering not wokring

### ISSUE THREAD

**Issue by dragma** [skratchdot/react-bootstrap-multiselect#28]
I can't manage to enable the filtering feature with my Multiselect react component.

Here is the code
```
 <Multiselect
                data={[{value:'My',selected:true},{value:'fake'},{value:'data'},{value:'is'},{value:'foobar'}]}
                includeSelectAllOption={true}
                [...]
                enableFiltering={true}
                [...]
                buttonClass='btn btn-whatever'
                multiple/>
```

Am I doing something wrong ?

**Comment by skratchdot** [comment]
Only these options are passed through: https://github.com/skratchdot/react-bootstrap-multiselect/commits/master/lib/get-options.js

There's probably a better way to do this, but this project was thrown together quickly.

I update those options by running `gulp get-options`: https://github.com/skratchdot/react-bootstrap-multiselect/commits/master/lib/get-options.js

**Comment by dragma** [comment]
Oh !
I'm confused. 
I don't know why I was sure that `enableFiltering` were listed in the `get-options.js`.
Thanks a lot for your time !
D.
--
PS : If someone else read this conversation because of the same problem, here is the answer : 
```
<Multiselect [...] enableCaseInsensitiveFiltering={true} [...] />
```
