### ISSUE TITLE
Invariant Violation: MultiSelect.render(): A valid ReactComponent must be returned.

### ISSUE THREAD

**Issue by boldt** [skratchdot/react-bootstrap-multiselect#36]
My project uses React 0.13.3. I added the following:

```
return (<Multiselect />);
```

I am getting the following error:

```
Invariant Violation: MultiSelect.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object
```

I guess it is an issue due to my older react version. Does your component work with React 0.13?

**Comment by skratchdot** [comment]
Version `0.6.0` still supports React 13.  I'm not sure why I updated to React 14 (if it was too hard to support both versions or what).

I'll bump a major version when new React versions come out I guess (still not sure the best way to keep up w/ React changes- but I see a few libraries that do it that way).

So:
React 13 should use: react-bootstrap-multiselect: 0.6.0
React 14 should use: react-bootstrap-multiselect: 1.2.0
React 15 (when out of beta) should use something like 2.0.0 (which doesn't exist yet).

**Comment by boldt** [comment]
Maybe add this version info to the README?

**Comment by skratchdot** [comment]
Good call.  I've updated the readme.
