### ISSUE TITLE
how to set default selected in list

### ISSUE THREAD

**Issue by jinggoing** [skratchdot/react-bootstrap-multiselect#60]
var data = [{value:1,label:'a'},{value:2,label:'b'}]
var tableList = [ {value:1,title:'t1'},{value:2,title:'t2'} ]

tableList.map((item, index){
// how to set Multiselect default selected by item.value
  <Multiselect   data={data}   />
})

**Comment by skratchdot** [comment]
You just need to set the `selected` property to true or false:

```javascript
var data = [{value:1,label:'a'},{value:2,label:'b'}]
var selectedValue = 2;

// set "selected" properties
console.log('before map:', data);
data = data.map((d) => {
  d.selected = d.value === selectedValue;
  return d;
});
console.log('after map:', data);
```
