### ISSUE TITLE
React v15.5 createClass() deprecation

### ISSUE THREAD

**Issue by audiolion** [skratchdot/react-bootstrap-multiselect#68]
React v15.5 is removing createClass() in favor of native es6 classes, is there any opposition to a PR to update react-bootstrap-multiselect to use es6 classes?

**Comment by skratchdot** [comment]
No. I'm all for it.  I haven't really done much w/ this library besides pull in PRs, so I've been wanting to spend some time one weekend cleaning it up (but haven't gotten around to it).
