### ISSUE TITLE
How to deselect options ?

### ISSUE THREAD

**Issue by yinfanguo** [skratchdot/react-bootstrap-multiselect#83]
The data for the two multiselect is the same, but you can't select the same option, so I should prompted and unselected when selecting the same option. I've seen that bootstrap-multiselect(http://davidstutz.de/bootstrap-multiselect/#methods) has a deselect method, but how can I use the react-bootstap-multiselect?

**Comment by sman591** [comment]
I accomplish this by storing a ref to the MultiSelect, and calling `syncData()` on it whenever the props change.

E.g:
```jsx
this.setState({ ...some data... })
this.multiselectRef.syncData()
```

**Comment by sman591** [comment]
See: https://github.com/skratchdot/react-bootstrap-multiselect#note-on-data-synchronization
